"""
SELECT
    MIN("observation.state"[1]) AS min_dim_1, MAX("observation.state"[1]) AS max_dim_1,
    MIN("observation.state"[2]) AS min_dim_2, MAX("observation.state"[2]) AS max_dim_2,
    MIN("observation.state"[3]) AS min_dim_3, MAX("observation.state"[3]) AS max_dim_3,
    MIN("observation.state"[4]) AS min_dim_4, MAX("observation.state"[4]) AS max_dim_4,
    MIN("observation.state"[5]) AS min_dim_5, MAX("observation.state"[5]) AS max_dim_5,
    MIN("observation.state"[6]) AS min_dim_6, MAX("observation.state"[6]) AS max_dim_6,
    MIN("observation.state"[7]) AS min_dim_7, MAX("observation.state"[7]) AS max_dim_7,
    MIN("observation.state"[8]) AS min_dim_8, MAX("observation.state"[8]) AS max_dim_8,
    MIN("observation.state"[9]) AS min_dim_9, MAX("observation.state"[9]) AS max_dim_9,
    MIN("observation.state"[10]) AS min_dim_10, MAX("observation.state"[10]) AS max_dim_10,
    MIN("observation.state"[11]) AS min_dim_11, MAX("observation.state"[11]) AS max_dim_11,
    MIN("observation.state"[12]) AS min_dim_12, MAX("observation.state"[12]) AS max_dim_12,
    MIN("observation.state"[13]) AS min_dim_13, MAX("observation.state"[13]) AS max_dim_13,
    MIN("observation.state"[14]) AS min_dim_14, MAX("observation.state"[14]) AS max_dim_14,
    MIN("observation.state"[15]) AS min_dim_15, MAX("observation.state"[15]) AS max_dim_15,
    MIN("observation.state"[16]) AS min_dim_16, MAX("observation.state"[16]) AS max_dim_16,
    MIN("observation.state"[17]) AS min_dim_17, MAX("observation.state"[17]) AS max_dim_17,
    MIN("observation.state"[18]) AS min_dim_18, MAX("observation.state"[18]) AS max_dim_18,
    MIN("observation.state"[19]) AS min_dim_19, MAX("observation.state"[19]) AS max_dim_19,
    MIN("observation.state"[20]) AS min_dim_20, MAX("observation.state"[20]) AS max_dim_20,
    MIN("observation.state"[21]) AS min_dim_21, MAX("observation.state"[21]) AS max_dim_21
FROM train;
"""
SELECT
    MIN("observation.state"[1]) AS min_dim_1,
    MIN("observation.state"[2]) AS min_dim_2,
    MIN("observation.state"[3]) AS min_dim_3,
    MIN("observation.state"[4]) AS min_dim_4,
    MIN("observation.state"[5]) AS min_dim_5,
    MIN("observation.state"[6]) AS min_dim_6,
    MIN("observation.state"[7]) AS min_dim_7,
    MIN("observation.state"[8]) AS min_dim_8,
    MIN("observation.state"[9]) AS min_dim_9,
    MIN("observation.state"[10]) AS min_dim_10,
    MIN("observation.state"[11]) AS min_dim_11,
    MIN("observation.state"[12]) AS min_dim_12,
    MIN("observation.state"[13]) AS min_dim_13,
    MIN("observation.state"[14]) AS min_dim_14,
    MIN("observation.state"[15]) AS min_dim_15,
    MIN("observation.state"[16]) AS min_dim_16,
    MIN("observation.state"[17]) AS min_dim_17,
    MIN("observation.state"[18]) AS min_dim_18,
    MIN("observation.state"[19]) AS min_dim_19,
    MIN("observation.state"[20]) AS min_dim_20,
    MIN("observation.state"[21]) AS min_dim_21,
    MAX("observation.state"[1]) AS max_dim_1,
    MAX("observation.state"[2]) AS max_dim_2,
    MAX("observation.state"[3]) AS max_dim_3,
    MAX("observation.state"[4]) AS max_dim_4,
    MAX("observation.state"[5]) AS max_dim_5,
    MAX("observation.state"[6]) AS max_dim_6,
    MAX("observation.state"[7]) AS max_dim_7,
    MAX("observation.state"[8]) AS max_dim_8,
    MAX("observation.state"[9]) AS max_dim_9,
    MAX("observation.state"[10]) AS max_dim_10,
    MAX("observation.state"[11]) AS max_dim_11,
    MAX("observation.state"[12]) AS max_dim_12,
    MAX("observation.state"[13]) AS max_dim_13,
    MAX("observation.state"[14]) AS max_dim_14,
    MAX("observation.state"[15]) AS max_dim_15,
    MAX("observation.state"[16]) AS max_dim_16,
    MAX("observation.state"[17]) AS max_dim_17,
    MAX("observation.state"[18]) AS max_dim_18,
    MAX("observation.state"[19]) AS max_dim_19,
    MAX("observation.state"[20]) AS max_dim_20,
    MAX("observation.state"[21]) AS max_dim_21
FROM train