SELECT
    MIN("action"[1]) AS min_dim_1,
    MIN("action"[2]) AS min_dim_2,
    MIN("action"[3]) AS min_dim_3,
    MIN("action"[4]) AS min_dim_4,
    MIN("action"[5]) AS min_dim_5,
    MIN("action"[6]) AS min_dim_6,
    MIN("action"[7]) AS min_dim_7,
    MIN("action"[8]) AS min_dim_8,
    MIN("action"[9]) AS min_dim_9,
    MIN("action"[10]) AS min_dim_10,
    MIN("action"[11]) AS min_dim_11,
    MIN("action"[12]) AS min_dim_12,
    MIN("action"[13]) AS min_dim_13,
    MIN("action"[14]) AS min_dim_14,
    MIN("action"[15]) AS min_dim_15,
    MIN("action"[16]) AS min_dim_16,
    MIN("action"[17]) AS min_dim_17,
    MIN("action"[18]) AS min_dim_18,
FROM train

SELECT
    MAX("action"[1]) AS max_dim_1,
    MAX("action"[2]) AS max_dim_2,
    MAX("action"[3]) AS max_dim_3,
    MAX("action"[4]) AS max_dim_4,
    MAX("action"[5]) AS max_dim_5,
    MAX("action"[6]) AS max_dim_6,
    MAX("action"[7]) AS max_dim_7,
    MAX("action"[8]) AS max_dim_8,
    MAX("action"[9]) AS max_dim_9,
    MAX("action"[10]) AS max_dim_10,
    MAX("action"[11]) AS max_dim_11,
    MAX("action"[12]) AS max_dim_12,
    MAX("action"[13]) AS max_dim_13,
    MAX("action"[14]) AS max_dim_14,
    MAX("action"[15]) AS max_dim_15,
    MAX("action"[16]) AS max_dim_16,
    MAX("action"[17]) AS max_dim_17,
    MAX("action"[18]) AS max_dim_18,
FROM train